### ISSUE TITLE
"init" script does not seem to be executed on new workspace creation

### ISSUE THREAD

**Issue by willdurand** [willdurand/gitpod-firefox-dev#3]
## STR

1. Open https://gitpod.io/#https://github.com/willdurand/gitpod-firefox-dev
2. Wait until there is no more activity in the terminal

## Expected

We have a `mozilla-unified/` directory in the workspace and Firefox can be run with `./mach run`.

## Actual

It looks like the init script isn't executed but it isn't clear why.

**Comment by willdurand** [comment]
@kemenaran hey, are you able to reproduce by chance? It's weird..

**Comment by kemenaran** [comment]
Yes, yesterday I had the same issue with the "before" script, which stops before being complete. I'll have a look at why (but I suspect some changes introduced in my latest PR)

**Comment by willdurand** [comment]
I figured out, I think. The last command in the `before` script returns a non-zero exit code when there is no Phabricator token.

**Comment by willdurand** [comment]
Erf, it took me more than a PR (and coffee..) to fix this issue but that is finally fixed!

**Comment by kemenaran** [comment]
Thank for fixing my mistakes :) Separate scripts look more maintainable in the long run indeed.
